import Head from "next/head";
import { useRouter } from "next/router";
import { ChangeEvent, FormEvent, useState } from "react";
import SearchForm from "../components/SearchForm";
import styles from "../styles/Home.module.scss";
import { HiOutlineSearch } from "react-icons/hi";

const Home = () => {
  const [inputValue, setInputValue] = useState("");
  const router = useRouter();
  const changeHandler = (event: ChangeEvent<HTMLInputElement>) => {
    setInputValue(event.currentTarget.value);
  };
  const submitHandler = (event: FormEvent) => {
    event.preventDefault();
    router.push({ pathname: `/search/${inputValue}` });
  };
  return (
    <main className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchForm submitHandler={submitHandler} changeHandler={changeHandler} />
    </main>
  );
};

export default Home;
